=== the-heapsters-account/duck-manager/lista-de-pedidos/src/plugin/extras/xml/model/model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="wish-list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="items">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="columns" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="column" type="xs:string"
                                            maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tag-values">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="columns-names">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="column-name" type="xs:string"
                                            maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="infos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tag" type="xs:string"
                                            maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== the-heapsters-account/duck-manager/lista-de-pedidos/src/java/createXML/xml/file_destiny.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wish-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="model.xsd">
    <items>
        <columns>
            <column codigo="código">0000000288</column>
            <column referencia="referência">F1-BA</column>
            <column codigo_barras="código de barras">7898578456649</column>
            <column nome="nome">MEIA DE COMPRESSAO BRANCO COM AZUL ACTE</column>
            <column preco_venda="preço">89</column>
            <column estoque="quantidade">1</column>
        </columns>
        <columns>
            <column codigo="código">0000000288</column>
            <column referencia="referência">F1-BA</column>
            <column codigo_barras="código de barras">7898578456649</column>
            <column nome="nome">MEIA DE COMPRESSAO BRANCO COM AZUL ACTE</column>
            <column preco_venda="preço">89</column>
            <column estoque="quantidade">1</column>
        </columns>
        <columns>
            <column codigo="código">0000000001</column>
            <column referencia="referência">0000000001</column>
            <column codigo_barras="código de barras">7896342452712</column>
            <column nome="nome">BOLSA PARA AGUA QUENTE MEDIA BORDO BC0013-BO MERCUR</column>
            <column preco_venda="preço">83</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000004</column>
            <column referencia="referência">B060035-AS</column>
            <column codigo_barras="código de barras">7896342450282</column>
            <column nome="nome">JOELHEIRA ESPORTE P  BC0035-AS MERCUR</column>
            <column preco_venda="preço">58</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000008</column>
            <column referencia="referência">B060045-AAS</column>
            <column codigo_barras="código de barras">7896342912117</column>
            <column nome="nome">TORNOZELEIRA ESPORTE PP BC0045-AAS MERCUR</column>
            <column preco_venda="preço">56</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000009</column>
            <column referencia="referência">B060045-AS</column>
            <column codigo_barras="código de barras">7896342450374</column>
            <column nome="nome">TORNOZELEIRA ESPORTE P BC0045-AS MERCUR</column>
            <column preco_venda="preço">56</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000012</column>
            <column referencia="referência">B060069-REC</column>
            <column codigo_barras="código de barras">7896342452224</column>
            <column nome="nome">TIPOIA ESTABILIZADORA ESTOFADA G BC0069-REC MERCUR </column>
            <column preco_venda="preço">75</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000017</column>
            <column referencia="referência">B060069-SIB</column>
            <column codigo_barras="código de barras">7896342452255</column>
            <column nome="nome">TIPOIA ORTOP M BC0069-SIB MERCUR</column>
            <column preco_venda="preço">59</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000021</column>
            <column referencia="referência">B060075-BS</column>
            <column codigo_barras="código de barras">7896342450459</column>
            <column nome="nome">COXAL ESPORTE M BC0075-BS MERCUR</column>
            <column preco_venda="preço">70</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000028</column>
            <column referencia="referência">B060104</column>
            <column codigo_barras="código de barras">7896342450787</column>
            <column nome="nome">CALEIRA PRO BC0104  MERCUR</column>
            <column preco_venda="preço">60</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000031</column>
            <column referencia="referência">B060162-AZ</column>
            <column codigo_barras="código de barras">7896342452569</column>
            <column nome="nome">COLAR CERVICAL LEVE AZUL P BC0162-AZ  MERCUR </column>
            <column preco_venda="preço">50</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000033</column>
            <column referencia="referência">B060162-CZ</column>
            <column codigo_barras="código de barras">7896342452583</column>
            <column nome="nome">COLAR CERVICAL LEVE AZUL G BC0162-CZ  MERCUR </column>
            <column preco_venda="preço">50</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000035</column>
            <column referencia="referência">B060400</column>
            <column codigo_barras="código de barras">7896342412365</column>
            <column nome="nome">DUCHA PARA HIGIENE INTIMA N10 BC0400 MERCUR </column>
            <column preco_venda="preço">61</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000038</column>
            <column referencia="referência">B060633-AP</column>
            <column codigo_barras="código de barras">7896342452859</column>
            <column nome="nome">JOELHEIRA ELASTICA PRETA P PAR BC0633-AP MERCUR</column>
            <column preco_venda="preço">48</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000040</column>
            <column referencia="referência">B060647-AP</column>
            <column codigo_barras="código de barras">7896342452941</column>
            <column nome="nome">TORNOZELEIRA ELASTICA P PRETA BC0647-AP MERCUR</column>
            <column preco_venda="preço">45</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000044</column>
            <column referencia="referência">B060656-A</column>
            <column codigo_barras="código de barras">7896342452286</column>
            <column nome="nome">ORTESE CURTA P/PUNHO C/TALA BEGE BILATERAL P BC0656 MERCUR</column>
            <column preco_venda="preço">79</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000051</column>
            <column referencia="referência">B060656-DP</column>
            <column codigo_barras="código de barras">7896342911943</column>
            <column nome="nome">ORTESE CURTA P/PUNHO C/TALA PRETO BILATERAL GG BC0656-DP MERCUR</column>
            <column preco_venda="preço">79</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000052</column>
            <column referencia="referência">B060660-AP</column>
            <column codigo_barras="código de barras">7896342453092</column>
            <column nome="nome">COTOVELEIRA ELASTICA PRETA P BC0660-AP MERCUR </column>
            <column preco_venda="preço">45</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000053</column>
            <column referencia="referência">B060660-BP</column>
            <column codigo_barras="código de barras">7896342453108</column>
            <column nome="nome">COTOVELEIRA ELASTICA PRETA M BC0660-BP MERCUR</column>
            <column preco_venda="preço">45</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000063</column>
            <column referencia="referência">B061001250001202</column>
            <column codigo_barras="código de barras">7896342414123</column>
            <column nome="nome">ORTESE P/JOELHO AJUSTAVEL  BC0031  MERCUR </column>
            <column preco_venda="preço">145</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000064</column>
            <column referencia="referência">B0610021522037</column>
            <column codigo_barras="código de barras">7896342415922</column>
            <column nome="nome">TORNOZELEIRA C/REFORCO M BC0047-B MERCUR</column>
            <column preco_venda="preço">73</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000066</column>
            <column referencia="referência">B061003150001</column>
            <column codigo_barras="código de barras">7896342416189</column>
            <column nome="nome">ORTESE PUNHO COM TALA PARA POLEGAR BC0055 MERCUR</column>
            <column preco_venda="preço">96</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000068</column>
            <column referencia="referência">B061507-IAM</column>
            <column codigo_barras="código de barras">7896342908738</column>
            <column nome="nome">MULETA CANADENSE FIXA INFANTIL AMARELA BC1507-IAM  MERCUR </column>
            <column preco_venda="preço">136</column>
            <column estoque="quantidade">0</column>
        </columns>
        <columns>
            <column codigo="código">0000000069</column>
